name: thelovekesh

recipe: wordpress

config:
  via: nginx
  webroot: wp
  database: mariadb:10.6
  composer_version: 2
  xdebug: off
  config:
    php: config/php.ini
    vhosts: config/nginx.conf

env_file:
  - .env

proxy:
  appserver_nginx:
    - local.thelovekesh.com

services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"
      image: thelovekesh/php:latest
    run:
      - setup-wordpress
      - cp config/wp-config.php wp/wp-config.php
  mailpit:
    type: lando
    app_mount: delegated
    moreHttpPorts:
      - 8025
    services:
      image: axllent/mailpit:latest
      volumes:
        - mailpit:/data
      ports:
        - 8025:8025
        - 1025:1025
      environment:
        MP_MAX_MESSAGES: 5000
        MP_DATA_FILE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
      command: '/mailpit'
    volumes:
      mailpit:
  pma:
    type: phpmyadmin
    hosts:
      - database
  nodejs:
    type: node:20
    scanner: false

tooling:
  wp:
    service: appserver
  npm:
    service: nodejs
  npx:
    service: nodejs
  node:
    service: nodejs
  composer:
    service: appserver
  git:
    service: appserver
  phpunit:
    service: appserver
  wp-logs:
    service: appserver
  setup-wordpress:
    service: appserver
  xdebug:
    service: appserver
    user: root
