name: thelovekesh

recipe: wordpress

config:
  php: 8.2
  via: nginx
  database: mariadb:10.6
  composer_version: 2
  xdebug: off
  config:
    php: config/php.ini

env_file:
  - .env.local
  - .env

proxy:
  appserver_nginx:
    - local.thelovekesh.com

services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"
    run:
      - bash bin/local-env/setup-wordpress.sh
    install_dependencies_as_root:
      - bash bin/local-env/install-dependencies.sh
  mailpit:
    type: lando
    app_mount: delegated
    services:
      image: axllent/mailpit:latest
      volumes:
        - mailpit:/data
      ports:
        - 8025:8025
        - 1025:1025
      environment:
        MP_MAX_MESSAGES: 5000
        MP_DATA_FILE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
      command: '/mailpit'
    volumes:
      mailpit:
  pma:
    type: phpmyadmin
    hosts:
      - database

tooling:
  wp:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver
  composer:
    service: appserver
  git:
    service: appserver
  phpunit:
    service: appserver
  wp-logs:
    service: appserver
    cmd:
      - tail -f /tmp/php-error.log 2>/dev/null || { echo "\e[31mNo logs found!\e[0m"; }
  xdebug:
    service: appserver
    cmd: bash bin/local-env/xdebug.sh
    user: root
